### PR TITLE
Improve CMakeList feature set and hide nvn impls to users

### PR DESCRIPTION
**Pull request by ThePixelGamer**
This PR was mainly created to move the Impl headers out of the public folders as to keep their intended design, these headers are now being included into a new TU nvn_Impl.cpp which relies on compile definitions to choose which to include

While messing with the cmake system I went ahead and readjusted the VER macros a little to be more readable and any projects that use these changes will need to change their current version setup
```
set(NN_SDK_MAJOR 4)
set(NN_SDK_MINOR 4)
set(NN_SDK_PATCH 0)

set(NN_WARE_MAJOR 1)
set(NN_WARE_MINOR 6)
set(NN_WARE_PATCH 1)
```
to this
```
set(NN_SDK 4.4.0)
set(NN_WARE 1.6.1)
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @leoetlino and @ThePixelGamer)

___
*[`CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42c2KC0qYH43S530ym:-O42c2KC0qYH43S530yn:byzy3df) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/CMakeLists.txt#L18)):*
> ```CMake
> if(NN_USE_GFX)
>   if(NN_API STREQUAL "C")
>     unset(NN_API)
> ```

Why do it like this? Wouldn't it be cleaner to keep this set like this, and from `gfx_NvnHelper` only include the `Base` instead of `Impl`?
___
*[`src/NintendoSDK/nvn/nvn_Impl.cpp` line 3 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42b-SmEbEPe6iUzEPV:-O42b-SmEbEPe6iUzEPW:bavjtwl) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/src/NintendoSDK/nvn/nvn_Impl.cpp#L3)):*
> ```cpp
> // included in gfx_NvnHelper.cpp
> #ifndef NN_API_C
> #include "nvn_FuncPtrImpl.h"
> ```

Are these still intended to be header files, or are those maybe just `cpp` files directly, which would also mean that they could be included/excluded in the CMake file instead?

**Comment by ThePixelGamer** [comment]
*[`CMakeLists.txt` line 18 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42c2KC0qYH43S530ym:-O42dIIJCHhCADY7S4KF:b-8phuga) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/CMakeLists.txt#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Why do it like this? Wouldn't it be cleaner to keep this set like this, and from `gfx_NvnHelper` only include the `Base` instead of `Impl`?
</blockquote></details>

In order for nvnLoadCProcs to be in the correct position in the SMO binary nvn_FuncPtrImpl is required to be include by gfx_NvnHelper.cpp

**Comment by ThePixelGamer** [comment]
*[`src/NintendoSDK/nvn/nvn_Impl.cpp` line 3 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42b-SmEbEPe6iUzEPV:-O42deYn83j-hw5iSwY-:b-ljdwon) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/src/NintendoSDK/nvn/nvn_Impl.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Are these still intended to be header files, or are those maybe just `cpp` files directly, which would also mean that they could be included/excluded in the CMake file instead?
</blockquote></details>

I approached this as CmakeLists being optional and more so just setup

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @leoetlino and @ThePixelGamer)

___
*[`src/NintendoSDK/nvn/nvn_Impl.cpp` line 1 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42hYaOAJwjbEMwz0zQ:-O42hYaOAJwjbEMwz0zR:bhr0civ) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/src/NintendoSDK/nvn/nvn_Impl.cpp#L1)):*
> ```cpp
> // included in gfx_NvnHelper.cpp
> ```

This comment is misleading

**Comment by ThePixelGamer** [comment]
*[`src/NintendoSDK/nvn/nvn_Impl.cpp` line 1 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42hYaOAJwjbEMwz0zQ:-O42idZs3TzMjLWhKcYw:bfslwrt) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/src/NintendoSDK/nvn/nvn_Impl.cpp#L1)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This comment is misleading
</blockquote></details>

It got addressed in the latest commit

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @leoetlino)

___
*[`src/NintendoSDK/nvn/nvn_Impl.cpp` line 1 at r1](https://reviewable.io/reviews/open-ead/nnheaders/32#-O42hYaOAJwjbEMwz0zQ:-O42kJkeBBMAJNsv5EHu:b-b34t34) ([raw file](https://github.com/open-ead/nnheaders/blob/74570de0617324e8943c5a6fcad695a66fa69aa9/src/NintendoSDK/nvn/nvn_Impl.cpp#L1)):*
<details><summary><i>Previously, ThePixelGamer (ThePixelCoder) wrote…</i></summary><blockquote>

It got addressed in the latest commit
</blockquote></details>

True, I missed that.

**Review by ThePixelGamer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: all files reviewed, 3 unresolved discussions (waiting on @leoetlino)

___
*[`CMakeLists.txt` line 5 at r3](https://reviewable.io/reviews/open-ead/nnheaders/32#-O4pCabs4RFPWCddEVOX:-O4pFeyt6Mpu0PPjYb6R:b-a5b58) ([raw file](https://github.com/open-ead/nnheaders/blob/dfb01e5424de7ef24d0351f2ad4535e66b9a2cd9/CMakeLists.txt#L5)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nit: maybe `NNSDK_GFX_TARGET`? IMO the name is a bit too generic right now
</blockquote></details>

I figured it would be better to leave it as a "global" define in case there's other areas in the SDK/Ware that have platform specific code (could also exclude the nvn API?)
___
*[`include/nn/util.h` line 28 at r3](https://reviewable.io/reviews/open-ead/nnheaders/32#-O4pD8Li9PkiTX-ajFnq:-O4pGv1R7xqd-waWtxra:b-ujq87e) ([raw file](https://github.com/open-ead/nnheaders/blob/dfb01e5424de7ef24d0351f2ad4535e66b9a2cd9/include/nn/util.h#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

please add parens around `major`, `minor` and `patch` (just to be safe)
</blockquote></details>

To support if a user passes in a statement with another operator? I didn't initially think about that due to just using integral constants atm
___
*[`include/nn/util.h` line 41 at r3](https://reviewable.io/reviews/open-ead/nnheaders/32#-O4pDMq08ZZcjy0VrZoD:-O4pGqlQD3nPA9JT9bjR:b-42fzil) ([raw file](https://github.com/open-ead/nnheaders/blob/1cc804966b3a45f46677b482c0a7338bd315a45c/include/nn/util.h#L41)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

why was the ifndef removed?
</blockquote></details>

This was an oversight on my part while I was redesigning this section

**Review by leoetlino — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: all files reviewed, 3 unresolved discussions (waiting on @ThePixelGamer)

___
*[`CMakeLists.txt` line 5 at r3](https://reviewable.io/reviews/open-ead/nnheaders/32#-O4pCabs4RFPWCddEVOX:-O4pIPrw-uZEEjZ65dXZ:b1p3sn3) ([raw file](https://github.com/open-ead/nnheaders/blob/dfb01e5424de7ef24d0351f2ad4535e66b9a2cd9/CMakeLists.txt#L5)):*
<details><summary><i>Previously, ThePixelGamer (ThePixelCoder) wrote…</i></summary><blockquote>

I figured it would be better to leave it as a "global" define in case there's other areas in the SDK/Ware that have platform specific code (could also exclude the nvn API?)
</blockquote></details>

I don't disagree with making this a global define, but what I'm saying is that the name is very generic and I think we should make it clearer that this is only for graphics.  for me, I'd expect the SDK target platform to be Horizon or Win32 or something like that

**Review by ThePixelGamer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @leoetlino and @MonsterDruide1)

___
*[`CMakeLists.txt` line 5 at r3](https://reviewable.io/reviews/open-ead/nnheaders/32#-O4pCabs4RFPWCddEVOX:-O4pgN-n5wEyICHuKyI-:bkj4s4k) ([raw file](https://github.com/open-ead/nnheaders/blob/dfb01e5424de7ef24d0351f2ad4535e66b9a2cd9/CMakeLists.txt#L5)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

I don't disagree with making this a global define, but what I'm saying is that the name is very generic and I think we should make it clearer that this is only for graphics.  for me, I'd expect the SDK target platform to be Horizon or Win32 or something like that
</blockquote></details>

I adjusted the system differently based on this, I feel like my changes simplifies this system a bit more

**Comment by leoetlino** [comment]
let me re-review this tonight

**Review by leoetlino — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: all files reviewed, 1 unresolved discussion (waiting on @ThePixelGamer)

___
*[`CMakeLists.txt` line 15 at r4](https://reviewable.io/reviews/open-ead/nnheaders/32#-O5KTHg35zwRpoZ8xFo8:-O5KTHg35zwRpoZ8xFo9:b-avkyl5) ([raw file](https://github.com/open-ead/nnheaders/blob/c0c3723d950d404cdc7c25d0c681aaf562fc8e8a/CMakeLists.txt#L15)):*
> ```CMake
> if(NN_GFX_TARGET)
>   # gfx_NvnHelper.cpp includes the C impl
> 	if(NVN_API STREQUAL "C")
> ```

nit: indentation looks a bit wacky here (I think this is a tab?)

**Review by leoetlino — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ThePixelGamer)

**Review by ThePixelGamer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32#-:-O5KrTXhBEo94rGdiRx1:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ThePixelGamer)

**Review by ThePixelGamer — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Review by ThePixelGamer — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/open-ead/nnheaders/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ThePixelGamer)

**Pull request merged**
